name: Crawl hydrodata(hbsl) schedulely

on:
  workflow_dispatch:	
  # push:
    # branches:
      # - main
  # schedule:
    # - cron: '8 16 */5 * *' # runs at 16:08 UTC every 5 days
  
  workflow_run:
    workflows: ['Crawl hydrodata(datong) schedulely']
    branches: [main]
    types:
      - completed

jobs:
  crawl-hbsl:
    #if: ${{ always() }}
    #needs: crawl-datong
    runs-on: ubuntu-latest	# access from github ip (us)
    steps:

      - name: checkout scripts repo
        uses: actions/checkout@v3
        
      - name: checkout data repo
        uses: actions/checkout@v3
        with: 
          repository: longavailable/hydrodata
          token: ${{ secrets.HYDRODATA_TOKEN }}
          path: data
        
      - name: checkout tool repo
        uses: actions/checkout@v3
        with:
          repository: longavailable/longs-python-toolbox
          path: mytool
          
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt

      - name: execute python script 003
        run: python 003-hydrodata-download-hbsl.py

      - name: commit and push data repo
        uses: longavailable/simple-push-action@longavailable
        with:
          repository: longavailable/hydrodata
          token: ${{ secrets.HYDRODATA_TOKEN }}
          path: data
          message: "Update hydrodata(hbsl) from Action `date`"
