name: Crawl hydrodata schedulely

on:
  push:
    branches:
      - main
  schedule:
    - cron: '8 8 */5 * *' # runs at 8:08 UTC every 5 days

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:

      - name: checkout scripts repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.HYDRODATA_TOKEN }}
        
      - name: checkout data repo
        uses: actions/checkout@v3
        with: 
          repository: longavailable/hydrodata
          path: data

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          
      - name: execute python script 002
        run: python 002-hydrodata-download-ahsxx-datong.py

      - name: execute python script 003
        run: python 003-hydrodata-download-hbsl.py

      - name: execute python script 004
        run: python 004-remove-nodata.py

      - name: commit and push data repo
        run: |
          cd data
          git config user.email github-actions@github.com
          git config user.name github-actions
          git add .
          git commit -m "Update hydrodata from Action `date`"
          git push
 
